// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nzpawvhmjetdxcvvbwbi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im56cGF3dmhtamV0ZHhjdnZid2JpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzNzEyNzUsImV4cCI6MjA2OTk0NzI3NX0.760Gi5Q5K0zNwNXyqcfwS6ksmJ4BlHr6AImM-VtA5nc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});